{
 "title": "RPi Throttling",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Activity",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Load5: $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "rack", "operator": "=", "value": "rpi" }
     ]
    },
    {
     "alias": "Active: $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "time_active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "rack", "operator": "=", "value": "rpi" }
     ]
    }
   ]
  },
  {
   "title": "Wireless Signal",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "Level: $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "wireless",
     "select": [
      [
       { "params": [ "level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "rack", "operator": "=", "value": "rpi" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "alias": "Mem Free: $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "rack", "operator": "=", "value": "rpi" }
     ]
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "alias": "Level: $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "rack", "operator": "=", "value": "rpi" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "mmcblk0p2" }
     ]
    }
   ]
  },
  {
   "title": "Throttle: Undervolted (Now)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rpi_throttling",
     "select": [
      [
       { "params": [ "now_undervolted" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "rack", "operator": "=", "value": "rpi" }
     ]
    }
   ]
  },
  {
   "title": "Throttle: Undervolted (Since Boot)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rpi_throttling",
     "select": [
      [
       { "params": [ "since_boot_undervolted" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "rack", "operator": "=", "value": "rpi" }
     ]
    }
   ]
  },
  {
   "title": "Throttle: ARM Freq Cap (Now)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rpi_throttling",
     "select": [
      [
       { "params": [ "now_arm_frequency_capped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "rack", "operator": "=", "value": "rpi" }
     ]
    }
   ]
  },
  {
   "title": "Throttle: ARM Freq Cap (Since Boot)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rpi_throttling",
     "select": [
      [
       {
        "params": [
         "since_boot_arm_frequency_capped"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "rack", "operator": "=", "value": "rpi" }
     ]
    }
   ]
  },
  {
   "title": "Throttle: Soft Temp Limit Reached (Now)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rpi_throttling",
     "select": [
      [
       { "params": [ "now_soft_temp_limit_reached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "rack", "operator": "=", "value": "rpi" }
     ]
    }
   ]
  },
  {
   "title": "Throttle: Soft Temp Limit Reached (Since Boot)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rpi_throttling",
     "select": [
      [
       {
        "params": [
         "since_boot_soft_temp_limit_reached"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "rack", "operator": "=", "value": "rpi" }
     ]
    }
   ]
  },
  {
   "title": "Throttle: Throttled (Since Boot)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rpi_throttling",
     "select": [
      [
       { "params": [ "now_throttled" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "rack", "operator": "=", "value": "rpi" }
     ]
    }
   ]
  },
  {
   "title": "Throttle: Throttled (Since Boot)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rpi_throttling",
     "select": [
      [
       { "params": [ "since_boot_throttled" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "rack", "operator": "=", "value": "rpi" }
     ]
    }
   ]
  }
 ]
}